name: Build and Release WASM

permissions:
  contents: write
on:
  release:
    types: [ published ]

env:
  EDGEE_API_TOKEN: ${{ secrets.EDGEE_API_TOKEN }}

jobs:
  check:
    name: Build and release wasm component
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-wasip2
      - uses: edgee-cloud/install-edgee-cli@v0.2.0
      - run: edgee component build
      - name: Upload WASM to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./amplitude.wasm
          asset_name: amplitude.wasm
          asset_content_type: application/wasm
      - name: Push to Edgee Component Registry
        run: edgee component push edgee --yes --changelog "${{ github.event.release.body }}"
